config/routes.rb
# notifun/config/routes.rb
Rails.application.routes.draw do
  namespace :notifun do
    resources :message_templates, param: :key do
      member do
        get :preview
      end
    end
    resources :messages, only: [:index, :show]
    resources :preferences, only: [:index] do
      collection do
        post :save
      end
    end
  end
end

app/models/notifun/message.rb
class Notifun::Message < ActiveRecord::Base
  self.table_name = 'notifun_messages'

  def message_template
    Notifun::MessageTemplate.where(key: message_template_key).first
  end
end

app/models/notifun/message_template.rb
class Notifun::MessageTemplate < ActiveRecord::Base
  self.table_name = 'notifun_message_templates'

  validates :key, uniqueness: true

  def to_param
    key
  end

  [:push_title, :push_body, :email_html, :email_text, :email_subject, :text_body].each do |method|
    define_method("merged_#{method}") do |merge_hash|
      merge(self.send(method), merge_hash)
    end

    define_method("preview_#{method}") do
      merge(self.send(method), merge_fields_preview)
    end
  end

  def messages
    Notifun::Message.where(message_template_key: key)
  end

  def default_notification_methods
    notification_methods = self[:default_notification_methods] & Notifun.configuration.notification_methods
    if notification_methods.empty?
      notification_methods = self[:backup_notification_methods] & Notifun.configuration.notification_methods
    end

    notification_methods
  end

  def backup_notification_methods
    (self[:backup_notification_methods] & Notifun.configuration.notification_methods) - default_notification_methods
  end

  def notification_methods
    default_notification_methods + backup_notification_methods
  end

  def possible_notification_methods
    array = []
    array << "push" if push_body.present?
    array << "email" if email_subject.present?
    array << "text" if text_body.present?

    if array.empty?
      notification_methods
    else
      array
    end
  end

  def push?
    notification_methods.include?("push")
  end

  def email?
    notification_methods.include?("email")
  end

  def sent_via
    text = default_notification_methods.join(' and ')
    if backup_notification_methods.any?
      text += " or "
      text += backup_notification_methods.join(', ')
    end

    text
  end

  def merge_fields_preview
    merge_fields.reduce({}){|hash, (k,v)| hash[k] = v["preview"].presence || v["description"] || v; hash}
  end

  def merge_fields_description
    merge_fields.reduce({}){|hash, (k,v)| hash[k] = v["description"] || v; hash}
  end

  def merge_fields_display
    text = []
    merge_fields_description.each do |key, description|
      text << "{#{key}} => #{description}"
    end
    text.join('<br>').html_safe
  end

  private

  def merge(text, merge_hash)
    text ||= ""
    merge_hash.each do |key, value|
      text.gsub!(/\{#{key}\}/, value)
    end

    text
  end
end

app/models/notifun/preference.rb
class Notifun::Preference < ActiveRecord::Base
  self.table_name = 'notifun_preferences'

  belongs_to :preferable, polymorphic: true

  def notification_methods
    array = []
    array << Notifun::NotificationMethods::EMAIL if email
    array << Notifun::NotificationMethods::PUSH if push
    array << Notifun::NotificationMethods::TEXT if text
    array & Notifun.configuration.notification_methods
  end
end

app/controllers/notifun/message_templates_controller.rb
class Notifun::MessageTemplatesController < Notifun.configuration.admin_parent_controller.constantize
  def index
    @message_templates = Notifun::MessageTemplate.all
  end

  def edit
    @message_template = Notifun::MessageTemplate.find_by_key(params[:key])
  end

  def update
    @message_template = Notifun::MessageTemplate.find_by_key(params[:key])
    if @message_template.update(message_template_attributes)
      redirect_to edit_notifun_message_template_path(@message_template), notice: "Message Template updated."
    else
      render :edit
    end
  end

  def preview
    @message_template = Notifun::MessageTemplate.find_by_key(params[:key])
    @notifun_models = @message_template.models

    render html: @message_template.preview_email_html.html_safe, layout: "mailer"
  end

  private

  def message_template_attributes
    params.require(:notifun_message_template).permit(:push_title, :push_body, :email_subject, :email_html, :email_text)
  end
end

app/controllers/notifun/messages_controller.rb
class Notifun::MessagesController < Notifun.configuration.admin_parent_controller.constantize
  def index
    limit = 100

    @page = (params[:page].presence || 1).to_i
    offset = limit * (@page - 1)
    @messages = Notifun::Message.order(created_at: :desc)
    @pages = (@messages.count / limit.to_f).ceil
    @messages = @messages.limit(limit).offset(offset)
  end

  def show
    @message = Notifun::Message.find(params[:id])
  end
end

app/controllers/notifun/preferences_controller.rb
class Notifun::PreferencesController < Notifun.configuration.user_parent_controller.constantize
  def index
    begin
      @models = self.send(Notifun.configuration.controller_method)
    rescue
      render text: "Notifun.configuration.controller_method is not set or not defined." and return
    end
    @models = [@models].flatten.compact
    if @models.empty?
      render text: "#{Notifun.configuration.controller_method} returned no models."
    end

    @notification_methods = Notifun.configuration.notification_methods.sort
  end

  def save
    params[:preferences].each do |index, preference_params|
      permitted_params = preference_params.slice(:preferable_type, :preferable_id, :category, :message_template_key, :email, :push, :text).permit!
      preference = Notifun::Preference.where(permitted_params.slice(:preferable_type, :preferable_id, preference_params[:preference_type])).first_or_initialize
      preference.attributes = permitted_params
      preference.save!
    end

    redirect_to notifun_preferences_path, notice: "Notification preferences saved."
  end
end

app/views/notifun/message_templates/edit.html.haml
- if Notifun.configuration.wysiwyg == "tinymce"
  = tinymce_assets
%h1 Edit #{@message_template.key.humanize} Message Template

= simple_form_for @message_template, html: { class: "two-columns" } do |f|
  .form-inputs
    = f.error_notification

    %p= @message_template.description
    %p Models: #{@message_template.models.join(', ')}
    %p Sent Via: #{@message_template.sent_via}
    %p Text surrounded by curly brackets "{example}" is replaced with info from the database when sent. The following are the keys you have available for replacement.
    .notifun-code-block= @message_template.merge_fields_display
    - if @message_template.push?
      = f.input :push_title, input_html: { class: 'notifun-code' }
      .input
        %label Push Title Preview
        .notifun-preview= @message_template.preview_push_title
      %br
      %br
      = f.input :push_body, input_html: { class: 'notifun-code' }
      .input
        %label Push Body Preview
        .notifun-preview= @message_template.preview_push_body
      %br
      %br
    - if @message_template.email?
      = f.input :email_subject, input_html: { class: 'notifun-code' }
      .input
        %label Email Subject Preview
        .notifun-preview= @message_template.preview_email_subject
      %br
      %br
      - if Notifun.configuration.wysiwyg == "tinymce"
        = f.input :email_html, input_html: { rows: 5, class: 'notifun-code tinymce', style: "height: 300px" }
        = tinymce
      - elsif Notifun.configuration.wysiwyg == "froala"
        = f.input :email_html, input_html: { rows: 5, class: 'notifun-code froala-editor', data: { froalaoptions: { heightMin: 300 }} }
      - else
        = f.input :email_html, input_html: { rows: 5, class: 'notifun-code' }
      .input
        %label Email HTML Preview
        .notifun-preview
          %iframe{height: "300px", width: "100%", src: preview_notifun_message_template_path(@message_template)}
      %br
      %br
      = f.input :email_text, input_html: { rows: 5, class: 'notifun-code' }
      .input
        %label Email Text Preview
        .notifun-preview= @message_template.preview_email_text

  .form-actions
    = f.button :submit

app/views/notifun/message_templates/index.html.haml
%h1 Message Templates

%table.notifun-table
  %thead
    %tr
      %th
      %th Sent via
      %th

  %tbody
    - @message_templates.where(category: nil).each do |message_template|
      %tr
        %td= message_template.description
        %td= message_template.sent_via
        - if message_template.editable
          %td= link_to "Edit", edit_notifun_message_template_path(message_template)
        - else
          %td
    - @message_templates.order(:category).pluck(:category).uniq.compact.each do |category|
      %tr
        %td.notifun-category.notifun-center{colspan: 3}= category.capitalize
      - @message_templates.order(:description).where(category: category).each do |message_template|
        %tr
          %td= message_template.description
          %td= message_template.sent_via
          - if message_template.editable
            %td= link_to "Edit", edit_notifun_message_template_path(message_template)
          - else
            %td

app/views/notifun/messages/index.haml
%h1 Messages

%table.table
  %thead
    %tr
      %th User
      %th Recipient
      %th Sent via
      %th Message Template
      %th Success
      %th Sent At
      %th

  %tbody
    - @messages.each do |message|
      - user = User.where(uuid: message.uuid).first
      %tr
        - if user.try(:display_name)
          %td= user.display_name
        - else
          %td= message.uuid
        %td= message.recipient
        %td= message.notification_method
        - if message.message_template
          %td= link_to message.message_template_key.humanize, edit_notifun_message_template_path(message.message_template)
        - else
          %td= message.message_template_key.humanize
        %td= message.success ? "Yes" : "No"
        %td= message.created_at.in_time_zone(Notifun.configuration.time_zone).strftime("%D %l:%M %Z")
        %td= link_to "View", message

.notifun-center
  - if @page == 1
    %span ← Previous
  - else
    = link_to '← Previous', { page: @page - 1 }

  - (1..@pages).each do |p|
    - if p == @page
      %em= @page
    - else
      = link_to p, { page: p }

  - if @page == @pages
    %span Next →
  - else
    = link_to 'Next →', { page: @page + 1 }

app/views/notifun/messages/show.haml
%h1 Message Details

.notifun-detail
  .notifun-detail-title UUID
  .notifun-detail-value= @message.uuid

.notifun-detail
  .notifun-detail-title Recipient
  .notifun-detail-value= @message.recipient

.notifun-detail
  .notifun-detail-title Sent Via
  .notifun-detail-value= @message.notification_method

.notifun-detail
  .notifun-detail-title Template
  .notifun-detail-value
    - if @message.message_template.editable
      = link_to @message.message_template_key.humanize, edit_notifun_message_template_path(@message.message_template)
    - else
      = @message.message_template_key.humanize

.notifun-detail
  .notifun-detail-title Sent At
  .notifun-detail-value= @message.created_at.in_time_zone(Notifun.configuration.time_zone).strftime("%D %l:%M %Z")

.notifun-detail
  .notifun-detail-title Success
  .notifun-detail-value= @message.success ? "Yes" : "No"

- if @message.error_message.present?
  .notifun-detail
    .notifun-detail-title Error Message
    .notifun-detail-value= @message.error_message

- if @message.data.present?
  .notifun-detail
    .notifun-detail-title Data
    .notifun-detail-value= @message.data

.notifun-detail
  .notifun-detail-title Title
  .notifun-detail-value= @message.message_title || "N/A"

.notifun-detail
  .notifun-detail-title Text
  .notifun-detail-value= @message.message_text

app/views/notifun/preferences/index.haml
%h1 Notification Preferences

= form_tag save_notifun_preferences_path, class: "notifun-form" do
  - @models.each do |model|
    - index = 0
    %h2 #{model.class.name} Preferences
    %table.notifun-table
      %thead
        %tr
          %th
          - @notification_methods.each do |notification_method|
            %th.notifun-center= notification_method.capitalize
      %tbody
        - message_templates = Notifun::MessageTemplate.where("models @> Array[?]::varchar[]", model.class.name).where("category IS NOT NULL")
        - message_templates.pluck(:category).uniq.each do |category|
          - prefix = "preferences[#{index}]"
          - index += 1
          - preference = Notifun::Preference.where(preferable: model, category: category).first_or_initialize
          = hidden_field_tag "#{prefix}[preferable_type]", model.class.name
          = hidden_field_tag "#{prefix}[preferable_id]", model.id
          = hidden_field_tag "#{prefix}[preference_type]", "category"
          = hidden_field_tag "#{prefix}[category]", category
          %tr
            %td.notifun-category #{category.capitalize} Category
            - @notification_methods.each do |notification_method|
              = hidden_field_tag "#{prefix}[#{notification_method}]", "0"
              %td.notifun-center= check_box_tag "#{prefix}[#{notification_method}]", "1", preference.send(notification_method)
          - message_templates.where(category: category).each do |message_template|
            - prefix = "preferences[#{index}]"
            - index += 1
            - preference = Notifun::Preference.where(preferable: model, message_template_key: message_template.key).first_or_initialize
            = hidden_field_tag "#{prefix}[preferable_type]", model.class.name
            = hidden_field_tag "#{prefix}[preferable_id]", model.id
            = hidden_field_tag "#{prefix}[preference_type]", "message_template_key"
            = hidden_field_tag "#{prefix}[message_template_key]", message_template.key
            %tr
              %td.notifun-indent= message_template.description
              - @notification_methods.each do |notification_method|
                = hidden_field_tag "#{prefix}[#{notification_method}]", "0"
                - checked = preference.persisted? ? preference.send(notification_method) : message_template.notification_methods.include?(notification_method)
                - if message_template.possible_notification_methods.include?(notification_method)
                  %td.notifun-center= check_box_tag "#{prefix}[#{notification_method}]", "1", checked
                - else
                  %td.notifun-center
  = submit_tag "Save Preferences"